module.exports=[
{slug:'mersin',title:'Mersin Oto Elektrikçi | Marş, Akü, Şarj & Yol Yardım',description:'Mersin oto elektrikçi: Yenişehir’de marş, akü, şarj dinamosu, tesisat ve elektronik arıza tespiti. 7/24 acil yol yardım: 0534 570 07 33.',eyebrow:'Yenişehir merkezli · Mersin',h1:'Mersin Oto Elektrikçi',intro:'Marş basmıyor, akü ışığı yanıyor veya aracınız elektrik arızası mı veriyor? SS Oto Elektrik & Aksesuar’a ulaşın; aracınıza uygun kontrol ve 7/24 acil yol yardım için doğrudan ustayla görüşün.',faq:[0,1,2,3,7],blocks:[
{heading:'Arızanın kaynağını birlikte netleştirelim.',paragraphs:['Araç elektrik arızalarında aynı belirti farklı nedenlerden kaynaklanabilir. Marşın yavaş dönmesi yalnızca aküyle, gösterge ışığının yanması yalnızca şarj dinamosuyla ilgili olmayabilir. Bu yüzden kontrole aracın belirtileri, bağlantıları ve gerekli ölçümlerle başlarız.','Yenişehir oto elektrikçi arayışınızda merkezimizle doğrudan iletişime geçebilirsiniz. Aracın marka, model, yıl bilgisi ve arızanın ne zaman başladığını paylaşmanız uygun kontrolü belirlememize yardımcı olur.'],items:['Marş sistemi ve marş motoru arızalarının kontrolü','Akü, kutup başları ve şarj sistemi ölçümleri','Şarj dinamosu ve bağlantı kontrolleri','Elektrik tesisatı, sigorta, röle ve elektrik kaçağı kontrolü','Elektronik arıza tespiti ve arıza kodlarının değerlendirilmesi']},
{heading:'En yakın oto elektrikçiyi ararken',paragraphs:['Mersin’de en yakın oto elektrikçi arıyorsanız önce konumunuzu paylaşın. Menteş Mahallesi’ndeki adresimize ulaşım veya bulunduğunuz yerde seyyar müdahale olanağını telefonla değerlendirelim. Mesafe ve ulaşım süresi için garanti vermek yerine mevcut duruma göre bilgi paylaşırız.','Araba elektrikçisi ya da araç elektrikçisi ihtiyacınızda arızanın belirtilerini söylemeniz önemlidir. Yanık kokusu, duman veya anormal ısınma varsa güvenli şekilde durun; elektrik sistemine müdahale etmeyin.']},
{heading:'Acil yol yardım için 7/24 ulaşın.',paragraphs:['Gece, hafta sonu veya pazar günü acil oto elektrikçi arıyorsanız yol yardım hattımızı arayabilirsiniz. Nöbetçi oto elektrikçi ihtiyacınız için konumunuz ve arızanız değerlendirilerek uygun seyyar hizmet bilgisi verilir.','7/24 ifadesi acil yol yardımı ve seyyar oto elektrik hizmetimiz içindir. Fiziksel dükkân ziyareti ve planlı servis için önceden telefonla görüşün. <a href="/hizmetler/7-24-oto-elektrik-yol-yardim/">Acil yol yardım hizmetini inceleyin.</a>']},
{heading:'Elektrik ve aksesuar aynı adreste.',paragraphs:['Arıza kontrolüne ek olarak Android ekran, araç kameraları, aydınlatma, klima kontrolü ve oto aksesuar uygulamaları sunuyoruz. <a href="/hizmetler/oto-aksesuar/">Mersin oto aksesuar hizmetlerimizi</a> inceleyerek aracınız için seçenekleri öğrenebilirsiniz.']}
]},
{slug:'7-24-oto-elektrik-yol-yardim',title:'Mersin 7/24 Acil Oto Elektrik Yol Yardım | SS Oto',description:'Mersin’de 7/24 acil oto elektrik yol yardım ve seyyar oto elektrikçi. Marş, akü ve elektrik arızalarında konumunuzu paylaşın, ustayla görüşün.',eyebrow:'7/24 acil yol yardımı · Seyyar oto elektrik',h1:'Yolda kaldığınızda,<br>doğrudan ustayı arayın.',intro:'Araç marş basmıyor veya elektrik arızası nedeniyle ilerleyemiyorsanız konumunuzu paylaşın. Mersin’de acil oto elektrik yol yardım hattımıza 7/24 ulaşabilirsiniz.',faq:[0,1,3,4,7],blocks:[
{heading:'Önce güvenli konum, sonra doğru yönlendirme.',paragraphs:['Aracınızı mümkünse güvenli bir alana alın. Trafiğe açık, müdahalenin riskli olduğu bir yerdeyseniz bunu ilk görüşmede belirtin. Kendinizi tehlikeye atarak araç üzerinde işlem yapmayın.','Aracın konumu, marş alıp almadığı, gösterge uyarıları ve yakın zamanda yapılan işlemler konuşularak seyyar müdahaleye uygunluk değerlendirilir. Ulaşım ve müdahale koşulları telefonla netleştirilir; sabit varış süresi taahhüt edilmez.']},
{heading:'Yerinde hangi kontroller yapılabilir?',paragraphs:['Bazı sorunlar araç başında incelenebilir. Kapsamlı sökme işlemleri veya güvenli çalışma alanı gerektiren arızalarda atölye incelemesi gerekebilir.'],items:['Akü kutup başları ve elektrik bağlantılarının kontrolü','Marş ve şarj sistemi belirtilerinin değerlendirilmesi','Uygun koşullarda sigorta ve röle kontrolleri','Erişilebilir tesisat bağlantılarının incelenmesi','Müdahale uygun değilse servis veya taşıma yönlendirmesi']},
{heading:'Pazar günü ve gece acil destek',paragraphs:['Pazar günü oto elektrikçi veya gece seyyar oto elektrikçi arayışınızda acil hattımızı kullanabilirsiniz. 7/24 hizmetimiz yol yardımı ve seyyar oto elektrik içindir; dükkânın sürekli açık olduğu anlamına gelmez.','Fiyat bilgisi konum, arıza ve gerekli işleme göre paylaşılır. İşlem ve parça ihtiyacı kontrol sonrası netleşebilir. <a href="/hizmetler/oto-elektrik-ariza-tespit/">Elektrik arıza tespiti hakkında bilgi alın.</a>']}
]},
{slug:'oto-elektrik-ariza-tespit',title:'Mersin Oto Elektrik Arıza Tespit | Marş, Şarj & Akü',description:'Mersin’de elektronik arıza tespit; marş motoru, şarj dinamosu, akü, tesisat, sigorta, röle ve elektrik kaçağı kontrolü. SS Oto Elektrik Yenişehir.',eyebrow:'Ölçüm · Kontrol · Bilgilendirme',h1:'Belirtiyi değil,<br>arızanın kaynağını ararız.',intro:'Marş, şarj, akü ve araç elektrik tesisatı sorunlarında gerekli kontrolleri yapalım. Mersin Yenişehir’de elektronik arıza tespiti için aracınızın bilgilerini paylaşın.',faq:[1,2,7],blocks:[
{heading:'Marş ve şarj sistemi kontrolü',paragraphs:['Kontak çevrildiğinde tık sesi gelmesi, marşın yavaş dönmesi ya da hiç dönmemesi; bağlantı, akü veya marş sistemi kaynaklı olabilir. Marş motoru değerlendirmesini ilgili besleme ve bağlantılarla birlikte yaparız.','Şarj dinamosu, bağlantılar ve şarj sistemi ölçümleri aküyle birlikte ele alınır. Akü ışığının yanması durumunda sorunun kaynağını ölçümle netleştirmek gerekir.']},
{heading:'Tesisat, sigorta ve elektrik kaçağı',paragraphs:['Tekrarlayan sigorta arızalarında sadece sigorta değiştirmek altta yatan sorunu çözmeyebilir. İlgili devre, röle ve bağlantılar kontrol edilir. Araca sonradan eklenen cihazlar da değerlendirmeye dahil edilebilir.'],items:['Araç elektrik tesisatında bağlantı ve hasar kontrolü','Sigorta ve rölelerin ilgili devrelerle değerlendirilmesi','Akü boşalmasına neden olabilen elektrik kaçağının kontrolü','Aydınlatma ve aksesuar bağlantılarının incelenmesi']},
{heading:'Elektronik arıza tespiti nasıl ilerler?',paragraphs:['Arıza kodları teşhise yardımcı olur; tek başına bir parçanın mutlaka değişmesi gerektiğini göstermez. Belirtiler, ölçümler ve aracın durumu birlikte değerlendirilir.','Araç marka/modelini, gösterge uyarılarını ve arızanın hangi koşullarda oluştuğunu aktarın. <a href="/iletisim/">İletişim formuyla WhatsApp mesajı hazırlayabilir</a> veya doğrudan arayabilirsiniz. Yolda kaldıysanız <a href="/hizmetler/7-24-oto-elektrik-yol-yardim/">7/24 acil yol yardım hattına</a> ulaşın.']}
]},
{slug:'oto-aksesuar',title:'Mersin Oto Aksesuar & Soner Cam | SS Oto Elektrik',description:'Mersin oto aksesuar, body kit, Android ekran, LED/xenon, araç kamerası ve Soner Cam oto cam hizmetleri. Araç uyumluluğu için bize ulaşın.',eyebrow:'Aksesuar · Multimedya · Soner Cam',h1:'Aracınıza uygun.<br>Size özel bir dokunuş.',intro:'Mersin Yenişehir’de oto aksesuar ve Soner Cam oto cam hizmetleri. Görünüm, kullanım ve konfor ihtiyaçlarınız için araç uyumluluğunu birlikte değerlendirelim.',faq:[5,6,7],blocks:[
{heading:'İhtiyacınıza göre aksesuar seçimi',paragraphs:['Ürün seçimini araç modeli, mevcut donanım ve kullanım alışkanlıklarınıza göre yapın. Montaj bağlantıları, ölçüler ve elektrik sistemine uyum uygulama öncesinde değerlendirilmelidir.'],items:['Android ekran ve multimedya sistemleri','Geri görüş, araç içi ve araç dışı kamera sistemleri','Xenon / LED aydınlatma uygulamaları','Body kit ve oto aksesuar uygulamaları','Soner Cam oto cam hizmetleri']},
{heading:'Body kit ve dış aksesuar uygulamaları',paragraphs:['Aracınızın marka, model ve yıl bilgisini paylaşarak istediğiniz uygulamayı tarif edin. Parça uyumu ve montaj imkânı araç özelinde değerlendirilir. Görsel örneklerinizi WhatsApp üzerinden iletebilirsiniz.','<a href="/hizmetler/android-ekran-ve-arac-kamerasi/">Android ekran ve kamera sistemleri</a> ile <a href="/hizmetler/far-ayari-ve-aydinlatma/">far ve aydınlatma hizmetlerimiz</a> için ilgili sayfalarda ayrıntı bulabilirsiniz.']},
{heading:'Soner Cam oto cam hizmetleri',paragraphs:['Oto cam ihtiyacınız için hasarın bulunduğu camı ve aracınızın bilgilerini paylaşın. Uygun işlem, ürün ve servis planı ön değerlendirme sonrasında konuşulur. Cam türü, stok, fiyat veya kesin işlem süresi hakkında bilgi almak için telefonla ulaşın.','Görüşü etkileyen cam hasarında aracın güvenli kullanımını önceliklendirin. İşlem kapsamı araç ve cam incelendikten sonra netleştirilir.']}
]},
{slug:'android-ekran-ve-arac-kamerasi',title:'Android Ekran & Araç Kamerası Mersin | SS Oto',description:'Mersin’de Android ekran, multimedya, geri görüş kamerası ve araç içi/dışı kamera montajı. Araç marka ve modelinize uygun seçenekler için arayın.',eyebrow:'Multimedya · Görüş · Sürüş konforu',h1:'Ekranınız yenilensin.<br>Sürüşünüz kolaylaşsın.',intro:'Android ekran, multimedya, geri görüş kamerası ve araç içi/dışı kamera sistemleri için araç uyumunu değerlendirelim. Mersin Yenişehir’de montaj bilgisi almak için ulaşın.',faq:[5,6,7],blocks:[
{heading:'Android ekran ve multimedya',paragraphs:['Android ekran seçerken yalnızca ekran boyutuna bakmak yeterli değildir. Konsol ölçüsü, soket yapısı, mevcut ses sistemi ve direksiyon kumandalarıyla uyum da değerlendirilir.','Telefon bağlantısı ve diğer özellikler seçilen ürüne göre değişir. Araç ve ürün belli olmadan belirli bir bağlantı özelliğinin ya da mevcut donanımın çalışacağını taahhüt etmeyiz.'],items:['Araç modeline uygun montaj çerçevesi ve bağlantı değerlendirmesi','Mevcut ses sistemi ve kumanda uyumunun kontrolü','İstenen işlevlere göre multimedya seçeneğinin belirlenmesi']},
{heading:'Geri görüş ve araç kameraları',paragraphs:['Geri görüş kamerasında montaj açısı, görüntü uyumu ve kablo güzergâhı birlikte değerlendirilir. Kamera, çevrenizi doğrudan kontrol etmenin yerine geçmez; sürüş sırasında dikkatli olun.','Araç içi ve araç dışı kamera uygulamalarında görüş alanı, güç bağlantısı ve kayıt özellikleri ürünün teknik özelliklerine göre belirlenir. Park halinde çalışma isteniyorsa aracın akü ve besleme koşulları ayrıca ele alınır.']},
{heading:'Bilgi almak için ne paylaşmalısınız?',paragraphs:['Araç marka, model ve yılını; mevcut ekranınızın olup olmadığını ve beklediğiniz işlevleri iletin. Konsol fotoğrafını WhatsApp görüşmesinde paylaşmanız ön değerlendirmeyi kolaylaştırır.','<a href="/hizmetler/oto-aksesuar/">Diğer oto aksesuar hizmetlerine</a> göz atabilir veya <a href="/iletisim/">iletişim sayfasından</a> mesaj hazırlayabilirsiniz.']}
]},
{slug:'far-ayari-ve-aydinlatma',title:'Mersin Far Ayarı & LED / Xenon Aydınlatma | SS Oto',description:'Mersin far ayarı, araç aydınlatma kontrolü, xenon ve LED uygulamaları. Far ve elektrik bağlantılarınız için SS Oto Elektrik Yenişehir’e ulaşın.',eyebrow:'Far ayarı · Xenon · LED',h1:'Yolu doğru ışıkla görün.',intro:'Far ayarı ve araç aydınlatma sistemleri için aracınıza uygun kontrol. Xenon ve LED uygulamalarında far yapısı ve elektrik bağlantıları birlikte değerlendirilir.',faq:[2,6,7],blocks:[
{heading:'Far ayarı neden kontrol edilir?',paragraphs:['Farların yönü, yolun aydınlatılması ve karşıdan gelen sürücünün görüşü açısından önemlidir. Aydınlatmanın yetersiz veya düzensiz olması durumunda ampul, far gövdesi, bağlantılar ve ayar birlikte kontrol edilmelidir.','Far değişimi, darbe veya aydınlatma şikâyeti sonrasında far ayarı ihtiyacını değerlendirmek için telefonla bilgi alabilirsiniz.']},
{heading:'Araç aydınlatma sistemleri',paragraphs:['Kesik kesik yanan, hiç yanmayan ya da normalden zayıf çalışan aydınlatmada elektrik bağlantıları da incelenir. Uygulama kapsamını aracın donanımı ve sorunun kaynağı belirler.'],items:['Far ayarı ve ışık yönü kontrolü','Far, sinyal ve araç aydınlatmalarının kontrolü','Soket, sigorta ve tesisat bağlantılarının değerlendirilmesi','Araç ve far yapısına uygun xenon / LED seçeneklerinin görüşülmesi']},
{heading:'Uygulama öncesi uyumluluk',paragraphs:['Her aydınlatma ürünü her far yapısına uygun olmayabilir. Seçenekler aracın özelliklerine ve kullanım koşullarına göre değerlendirilir; sadece daha parlak olmasına göre ürün seçilmez.','Aracınızın marka/modelini ve aydınlatma ihtiyacını paylaşın. Başka elektrik belirtileri de varsa <a href="/hizmetler/oto-elektrik-ariza-tespit/">oto elektrik arıza tespiti</a> kapsamında inceleyelim.']}
]},
{slug:'oto-klima',title:'Mersin Oto Klima Sistemi Kontrolü | SS Oto Elektrik',description:'Mersin Yenişehir’de oto klima sistemi, fan, kumanda ve elektrik bağlantısı kontrolü. Soğutma ve çalışma şikâyetiniz için SS Oto Elektrik’i arayın.',eyebrow:'Oto klima · Sistem kontrolü',h1:'Sürüş konforunu<br>yeniden hissedin.',intro:'Klima çalışmıyor, fan tepki vermiyor veya sistem düzensiz mi çalışıyor? Araç klima sisteminin kontrolü için belirtileri paylaşın, uygun incelemeyi belirleyelim.',faq:[6,7],blocks:[
{heading:'Klima şikâyetini doğru tarif edin.',paragraphs:['Klima sorunları her zaman aynı nedenden kaynaklanmaz. Havanın hiç gelmemesi, hava gelip soğutmaması veya sistemin aralıklı çalışması farklı kontroller gerektirebilir.','Şikâyetin ne zaman başladığını, fan kademelerinin çalışıp çalışmadığını ve gösterge panelindeki belirtileri paylaşmanız ön değerlendirmeyi kolaylaştırır.']},
{heading:'Elektrik ve kumanda kontrolleri',paragraphs:['Klima sistemi kontrolünde aracın donanımına göre ilgili elektrik bağlantıları, kumanda tepkileri ve fan çalışması değerlendirilir. Gerekli diğer işlemlerin kapsamı incelemeyle netleştirilir.'],items:['Klima kumandası ve fan çalışmasının kontrolü','İlgili sigorta, röle ve bağlantıların değerlendirilmesi','Aracın belirtilerine göre sistem incelemesi','Gerekli işlem ve yönlendirme hakkında bilgilendirme']},
{heading:'Servis planını birlikte yapalım.',paragraphs:['Klima için gerekli parça, işlem ve fiyat araç kontrolüne göre değişir. Gelmeden önce telefonla görüşerek servis uygunluğunu öğrenin.','Başka elektrik sorunları da yaşıyorsanız <a href="/hizmetler/oto-elektrik-ariza-tespit/">oto elektrik ve arıza tespit hizmetimizi</a> inceleyebilirsiniz. <a href="/iletisim/">İletişim ve yol tarifi bilgilerine ulaşın.</a>']}
]}
];
