const {chromium}=require('playwright');
const AxeBuilder=require('@axe-core/playwright').default;
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const base='http://127.0.0.1:4173';const dist=path.resolve(__dirname,'../dist');const out=path.resolve(__dirname,'../qa');fs.mkdirSync(out,{recursive:true});
const files=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(p.endsWith('.html'))files.push(p);}}walk(dist);
const routes=files.map(f=>'/'+path.relative(dist,f).split(path.sep).join('/').replace(/index\.html$/,''));
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const ctx=await browser.newContext();const page=await ctx.newPage();const errors=[];const report={routes:[],screens:[],checks:[],consoleErrors:errors};
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',msg=>{if(msg.type()==='error'&&!msg.text().includes('Failed to load resource'))errors.push(msg.text());});
 const titles=new Set(),descriptions=new Set(),internal=new Set();
 for(const route of routes){await page.goto(base+route,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);
  const data=await page.evaluate(()=>({title:document.title,description:document.querySelector('meta[name=description]')?.content,h1:document.querySelectorAll('h1').length,lang:document.documentElement.lang,canonical:document.querySelector('link[rel=canonical]')?.href,ids:[...document.querySelectorAll('[id]')].map(e=>e.id),links:[...document.querySelectorAll('a')].map(e=>({href:e.getAttribute('href'),id:e.id,track:e.dataset.track})),assets:[...document.querySelectorAll('script[src],link[rel=stylesheet],img')].map(e=>e.getAttribute('src')||e.getAttribute('href')),imgs:[...document.images].map(i=>({complete:i.complete&&i.naturalWidth>0,alt:i.alt,width:i.getAttribute('width'),height:i.getAttribute('height')})),schemas:[...document.querySelectorAll('script[type="application/ld+json"]')].flatMap(e=>JSON.parse(e.textContent)),faq:[...document.querySelectorAll('.faq-list details')].map(d=>[d.querySelector('summary').textContent,d.querySelector('p').textContent])}));
  assert.equal(data.h1,1,route+' H1');assert.equal(data.lang,'tr');assert(data.description);assert(!titles.has(data.title),'duplicate title');assert(!descriptions.has(data.description),'duplicate description');titles.add(data.title);descriptions.add(data.description);assert.equal(new Set(data.ids).size,data.ids.length,route+' duplicate IDs');assert.equal(data.canonical,'https://ssotoelektrik.com.tr'+route);
  for(const link of data.links){assert(link.href&&link.href!=='#','empty link');if(link.href.startsWith('/')&&!link.href.startsWith('//'))internal.add(link.href.split('#')[0]);if(link.href.startsWith('tel:')){assert.equal(link.href,'tel:+905345700733');assert.equal(link.track,'phone_click');assert(link.id);}if(link.href.includes('wa.me/')){assert.equal(new URL(link.href).pathname,'/905345700733');assert(new URL(link.href).searchParams.get('text'));assert.equal(link.track,'whatsapp_click');assert(link.id);}if(link.href.includes('google.com/maps/dir/')){assert(new URL(link.href).searchParams.get('destination').includes('Yenişehir'));assert.equal(link.track,'directions_click');assert(link.id);}}
  for(const asset of data.assets){if(asset.startsWith('/'))internal.add(asset.split('?')[0]);}
  for(const img of data.imgs){assert(img.alt&&img.width&&img.height,'image metadata');}
  const faq=data.schemas.find(s=>s['@type']==='FAQPage');if(faq)assert.deepEqual(faq.mainEntity.map(e=>[e.name,e.acceptedAnswer.text]),data.faq);
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  report.routes.push({route,title:data.title,accessibility:axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});
  console.log('PAGE',route,'A11Y violations:',axe.violations.length);
 }
 for(const link of internal){const r=await ctx.request.get(base+link);assert(r.ok(),`Broken local URL ${link}: ${r.status()}`);}
 report.checks.push(`${internal.size} internal routes/assets return HTTP 200`,`${routes.length} unique page titles, descriptions, H1, canonical and IDs`, 'All telephone, WhatsApp, directions hrefs and FAQ schemas checked');
 for(const width of [360,768,1024,1440]){await page.setViewportSize({width,height:900});for(const route of routes){await page.goto(base+route,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route+' overflow at '+width);}await page.goto(base,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,`home-${width}.png`)});report.screens.push({width,pages:routes.length,overflow:false});}
 await page.setViewportSize({width:360,height:800});await page.goto(base);const heroBox=await page.locator('#hero-phone').boundingBox();assert(heroBox.y+heroBox.height<800,'First mobile screen phone CTA');
 await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');await page.locator('.site-nav details summary').click();assert(await page.locator('.dropdown-links').isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');await page.locator('.menu-toggle').click();await page.locator('.site-nav a[href="/iletisim/"]').click();assert(page.url().endsWith('/iletisim/'));assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');report.checks.push('Mobile menu opens, nested service menu works, Escape closes, navigation works');
 await page.setViewportSize({width:1440,height:900});await page.goto(base);await page.evaluate(()=>document.addEventListener('click',e=>{if(e.target.closest('[data-track]'))e.preventDefault();},true));
 for(const [id,name] of [['hero-phone','phone_click'],['hero-whatsapp','whatsapp_click'],['hero-directions','directions_click']]){await page.evaluate(()=>window.dataLayer=[]);await page.locator('#'+id).click();const events=await page.evaluate(()=>window.dataLayer);assert.equal(events.length,1);assert.equal(events[0].event,name);assert.equal(events[0].cta_id,id);}
 report.checks.push('Phone, WhatsApp and directions user clicks create exactly one matching dataLayer event');
 await page.goto(base+'/iletisim/');await page.evaluate(()=>{window.__opened=[];window.open=(url)=>{window.__opened.push(url);return null;};window.dataLayer=[];});
 await page.locator('#contact-form-submit').click();assert.equal(await page.evaluate(()=>window.__opened.length),0);
 await page.locator('[name=name]').fill('Test Kullanıcı');await page.locator('[name=phone]').fill('000');await page.locator('[name=vehicle]').fill('Renault Clio, 2018');await page.locator('[name=problem]').fill('Marş basmıyor. Türkçe: ş ğ ü ö ç ı & + ?');await page.locator('[name=consent]').check();await page.locator('#contact-form-submit').click();assert.equal(await page.evaluate(()=>window.__opened.length),0);
 await page.locator('[name=phone]').fill('0534 000 00 00');await page.locator('[name=consent]').uncheck();await page.locator('#contact-form-submit').click();assert.equal(await page.evaluate(()=>window.__opened.length),0);
 await page.locator('[name=consent]').check();await page.locator('#contact-form-submit').click();const formResult=await page.evaluate(()=>({urls:window.__opened,events:window.dataLayer,status:document.querySelector('.form-status').textContent}));assert.equal(formResult.urls.length,1);const u=new URL(formResult.urls[0]);assert.equal(u.pathname,'/905345700733');const message=u.searchParams.get('text');assert(message.includes('Türkçe: ş ğ ü ö ç ı & + ?'));assert(message.includes('Test Kullanıcı'));assert.equal(formResult.events.length,1);assert.equal(formResult.events[0].event,'lead_form_submit');assert(!JSON.stringify(formResult.events).includes('Test Kullanıcı'));report.checks.push('Empty/invalid/no-consent forms blocked; valid form creates correctly URL-encoded WhatsApp message; no PII in dataLayer');
 await page.goto(base+'/hizmetler/oto-elektrik-ariza-tespit/');const first=page.locator('.faq-list details').first();await first.locator('summary').click();assert(await first.getAttribute('open')!==null);await first.locator('summary').click();assert.equal(await first.getAttribute('open'),null);report.checks.push('FAQ expand/collapse');
 const missing=await ctx.request.get(base+'/bu-sayfa-yok/');assert.equal(missing.status(),404);assert((await missing.text()).includes('Bu yol bir yere çıkmıyor'));report.checks.push('Missing routes return real HTTP 404 with custom page');
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base);assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');assert.equal(await page.locator('.will-reveal').count(),0);report.checks.push('Reduced motion respected');
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log('Browser errors:',JSON.stringify(errors));assert.equal(errors.length,0,'Browser JS errors');
 await page.setViewportSize({width:1440,height:1000});await page.goto(base,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);await page.locator('.contact-section').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'home-full-desktop.png'),fullPage:true});await page.locator('.accessories').screenshot({path:path.join(out,'accessories-desktop.png')});await page.locator('.contact-section').screenshot({path:path.join(out,'contact-desktop.png')});
 await page.setViewportSize({width:360,height:800});await page.goto(base+'/iletisim/',{waitUntil:'domcontentloaded'});await page.locator('.contact-form').screenshot({path:path.join(out,'contact-form-mobile.png')});
 await browser.close();console.log('QA complete. Report: qa/report.json');
 if(report.routes.some(r=>r.accessibility.length))process.exitCode=2;
})().catch(e=>{console.error(e);process.exit(1);});
